/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 80,
  overrides: [{ files: "*.json", options: { printWidth: 1000 } }],
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "",
    "// shadcn",
    "^@/components/ui/(.*)$",
    "",
    "// third-party",
    "<THIRD_PARTY_MODULES>",
    "",
    "// project imports",
    "^@/(?!types/)(.*)$",
    "^[.](?!.*types)(.*)$",
    "",
    "// assets",
    "^(lucide-react|@tabler/icons-react)$",
    "",
    "// types",
    "^@/types/(.*)$",
    "^[.].*types(.*)$",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderTypeScriptVersion: "5.0.0",
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  tailwindStylesheet: "./src/app/globals.css",
  tailwindFunctions: ["cn", "cva"],
}
